name: Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Esto ejecutará los tests en una máquina Ubuntu
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'  # Usa la versión de PHP que necesites

      - name: Install Composer dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --prefer-dist --no-interaction

      - name: Set up environment
        run: |
          cp .env.example .env
          php artisan key:generate

